# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    # TODO: Once west supports sparse checkout, we should use it here.
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      revision: 82d06c118043d6f4dec965d3bf40abafc232735a
