# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    # TODO: Once west supports sparse checkout, we should use it here.
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      revision: 6c2f4ec7b8916e89cbce66cd0ad82df7642d6f78
